/**
 * Libellés des 88 DIVISIONS de la nomenclature NAF rév. 2 (INSEE) — les deux
 * premiers chiffres du code APE (« 68.31Z » → division « 68 »).
 *
 * Lot 2 UX (audit du 02/10/2026) : la liste des entreprises affichait
 * « Top NAF 68.31Z », un code que le propriétaire de la console n'a pas à
 * connaître. Le code complet (732 sous-classes) n'a pas de libellé côté API ;
 * la division suffit à dire « de quoi il s'agit » : « Activités immobilières ».
 */
export const DIVISIONS_NAF: Readonly<Record<string, string>> = {
  '01': 'Agriculture et élevage',
  '02': 'Sylviculture et exploitation forestière',
  '03': 'Pêche et aquaculture',
  '05': 'Extraction de houille et de lignite',
  '06': 'Extraction d’hydrocarbures',
  '07': 'Extraction de minerais métalliques',
  '08': 'Autres industries extractives',
  '09': 'Services de soutien aux industries extractives',
  '10': 'Industries alimentaires',
  '11': 'Fabrication de boissons',
  '12': 'Fabrication de produits à base de tabac',
  '13': 'Fabrication de textiles',
  '14': 'Industrie de l’habillement',
  '15': 'Industrie du cuir et de la chaussure',
  '16': 'Travail du bois',
  '17': 'Industrie du papier et du carton',
  '18': 'Imprimerie et reproduction',
  '19': 'Cokéfaction et raffinage',
  '20': 'Industrie chimique',
  '21': 'Industrie pharmaceutique',
  '22': 'Produits en caoutchouc et en plastique',
  '23': 'Autres produits minéraux non métalliques',
  '24': 'Métallurgie',
  '25': 'Fabrication de produits métalliques',
  '26': 'Produits informatiques, électroniques et optiques',
  '27': 'Fabrication d’équipements électriques',
  '28': 'Fabrication de machines et équipements',
  '29': 'Industrie automobile',
  '30': 'Fabrication d’autres matériels de transport',
  '31': 'Fabrication de meubles',
  '32': 'Autres industries manufacturières',
  '33': 'Réparation et installation de machines',
  '35': 'Électricité, gaz et vapeur',
  '36': 'Captage, traitement et distribution d’eau',
  '37': 'Collecte et traitement des eaux usées',
  '38': 'Collecte, traitement et recyclage des déchets',
  '39': 'Dépollution',
  '41': 'Construction de bâtiments',
  '42': 'Génie civil',
  '43': 'Travaux de construction spécialisés',
  '45': 'Commerce et réparation automobiles',
  '46': 'Commerce de gros',
  '47': 'Commerce de détail',
  '49': 'Transports terrestres',
  '50': 'Transports par eau',
  '51': 'Transports aériens',
  '52': 'Entreposage et services auxiliaires des transports',
  '53': 'Activités de poste et de courrier',
  '55': 'Hébergement',
  '56': 'Restauration',
  '58': 'Édition',
  '59': 'Cinéma, vidéo, télévision, musique',
  '60': 'Programmation et diffusion',
  '61': 'Télécommunications',
  '62': 'Programmation et conseil informatiques',
  '63': 'Services d’information',
  '64': 'Services financiers',
  '65': 'Assurance',
  '66': 'Auxiliaires de services financiers et d’assurance',
  '68': 'Activités immobilières',
  '69': 'Activités juridiques et comptables',
  '70': 'Sièges sociaux et conseil de gestion',
  '71': 'Architecture et ingénierie',
  '72': 'Recherche-développement scientifique',
  '73': 'Publicité et études de marché',
  '74': 'Autres activités spécialisées, scientifiques et techniques',
  '75': 'Activités vétérinaires',
  '77': 'Location et location-bail',
  '78': 'Activités liées à l’emploi',
  '79': 'Agences de voyage et voyagistes',
  '80': 'Enquêtes et sécurité',
  '81': 'Services relatifs aux bâtiments et aménagement paysager',
  '82': 'Services administratifs et de soutien aux entreprises',
  '84': 'Administration publique',
  '85': 'Enseignement',
  '86': 'Activités pour la santé humaine',
  '87': 'Hébergement médico-social et social',
  '88': 'Action sociale sans hébergement',
  '90': 'Activités créatives, artistiques et de spectacle',
  '91': 'Bibliothèques, archives, musées',
  '92': 'Jeux de hasard et d’argent',
  '93': 'Activités sportives, récréatives et de loisirs',
  '94': 'Activités des organisations associatives',
  '95': 'Réparation d’ordinateurs et de biens personnels',
  '96': 'Autres services personnels',
  '97': 'Ménages employeurs de personnel domestique',
  '98': 'Ménages producteurs pour usage propre',
  '99': 'Organisations extraterritoriales',
};

/** Libellé lisible d'un code NAF/APE (« 68.31Z » → « Activités immobilières »), ou `null`. */
export function libelleNaf(code: string | null | undefined): string | null {
  if (code === null || code === undefined) return null;
  const division = code.replace(/[^0-9]/g, '').slice(0, 2);
  return DIVISIONS_NAF[division] ?? null;
}
