/**
 * Source de référence des zones administratives françaises.
 * Évite de dépendre d'un endpoint backend (qui ne retourne que les cells
 * déjà scrappées via /coverage). Hardcodé = stable, zéro latence, zéro fail.
 *
 * Source : INSEE (codes officiels). Données figées au 2026-05-17.
 */

export interface FrZone { code: string; name: string }

/** 96 départements métropolitains + 5 DROM = 101 départements. */
export const FR_DEPARTMENTS: ReadonlyArray<FrZone> = [
  { code: '01', name: 'Ain' },
  { code: '02', name: 'Aisne' },
  { code: '03', name: 'Allier' },
  { code: '04', name: 'Alpes-de-Haute-Provence' },
  { code: '05', name: 'Hautes-Alpes' },
  { code: '06', name: 'Alpes-Maritimes' },
  { code: '07', name: 'Ardèche' },
  { code: '08', name: 'Ardennes' },
  { code: '09', name: 'Ariège' },
  { code: '10', name: 'Aube' },
  { code: '11', name: 'Aude' },
  { code: '12', name: 'Aveyron' },
  { code: '13', name: 'Bouches-du-Rhône' },
  { code: '14', name: 'Calvados' },
  { code: '15', name: 'Cantal' },
  { code: '16', name: 'Charente' },
  { code: '17', name: 'Charente-Maritime' },
  { code: '18', name: 'Cher' },
  { code: '19', name: 'Corrèze' },
  { code: '2A', name: 'Corse-du-Sud' },
  { code: '2B', name: 'Haute-Corse' },
  { code: '21', name: "Côte-d'Or" },
  { code: '22', name: "Côtes-d'Armor" },
  { code: '23', name: 'Creuse' },
  { code: '24', name: 'Dordogne' },
  { code: '25', name: 'Doubs' },
  { code: '26', name: 'Drôme' },
  { code: '27', name: 'Eure' },
  { code: '28', name: 'Eure-et-Loir' },
  { code: '29', name: 'Finistère' },
  { code: '30', name: 'Gard' },
  { code: '31', name: 'Haute-Garonne' },
  { code: '32', name: 'Gers' },
  { code: '33', name: 'Gironde' },
  { code: '34', name: 'Hérault' },
  { code: '35', name: 'Ille-et-Vilaine' },
  { code: '36', name: 'Indre' },
  { code: '37', name: 'Indre-et-Loire' },
  { code: '38', name: 'Isère' },
  { code: '39', name: 'Jura' },
  { code: '40', name: 'Landes' },
  { code: '41', name: 'Loir-et-Cher' },
  { code: '42', name: 'Loire' },
  { code: '43', name: 'Haute-Loire' },
  { code: '44', name: 'Loire-Atlantique' },
  { code: '45', name: 'Loiret' },
  { code: '46', name: 'Lot' },
  { code: '47', name: 'Lot-et-Garonne' },
  { code: '48', name: 'Lozère' },
  { code: '49', name: 'Maine-et-Loire' },
  { code: '50', name: 'Manche' },
  { code: '51', name: 'Marne' },
  { code: '52', name: 'Haute-Marne' },
  { code: '53', name: 'Mayenne' },
  { code: '54', name: 'Meurthe-et-Moselle' },
  { code: '55', name: 'Meuse' },
  { code: '56', name: 'Morbihan' },
  { code: '57', name: 'Moselle' },
  { code: '58', name: 'Nièvre' },
  { code: '59', name: 'Nord' },
  { code: '60', name: 'Oise' },
  { code: '61', name: 'Orne' },
  { code: '62', name: 'Pas-de-Calais' },
  { code: '63', name: 'Puy-de-Dôme' },
  { code: '64', name: 'Pyrénées-Atlantiques' },
  { code: '65', name: 'Hautes-Pyrénées' },
  { code: '66', name: 'Pyrénées-Orientales' },
  { code: '67', name: 'Bas-Rhin' },
  { code: '68', name: 'Haut-Rhin' },
  { code: '69', name: 'Rhône' },
  { code: '70', name: 'Haute-Saône' },
  { code: '71', name: 'Saône-et-Loire' },
  { code: '72', name: 'Sarthe' },
  { code: '73', name: 'Savoie' },
  { code: '74', name: 'Haute-Savoie' },
  { code: '75', name: 'Paris' },
  { code: '76', name: 'Seine-Maritime' },
  { code: '77', name: 'Seine-et-Marne' },
  { code: '78', name: 'Yvelines' },
  { code: '79', name: 'Deux-Sèvres' },
  { code: '80', name: 'Somme' },
  { code: '81', name: 'Tarn' },
  { code: '82', name: 'Tarn-et-Garonne' },
  { code: '83', name: 'Var' },
  { code: '84', name: 'Vaucluse' },
  { code: '85', name: 'Vendée' },
  { code: '86', name: 'Vienne' },
  { code: '87', name: 'Haute-Vienne' },
  { code: '88', name: 'Vosges' },
  { code: '89', name: 'Yonne' },
  { code: '90', name: 'Territoire de Belfort' },
  { code: '91', name: 'Essonne' },
  { code: '92', name: 'Hauts-de-Seine' },
  { code: '93', name: 'Seine-Saint-Denis' },
  { code: '94', name: 'Val-de-Marne' },
  { code: '95', name: "Val-d'Oise" },
  // DROM
  { code: '971', name: 'Guadeloupe' },
  { code: '972', name: 'Martinique' },
  { code: '973', name: 'Guyane' },
  { code: '974', name: 'La Réunion' },
  { code: '976', name: 'Mayotte' },
];

/** 13 régions métropolitaines + 5 DROM régions = 18. */
export const FR_REGIONS: ReadonlyArray<FrZone> = [
  { code: '84', name: 'Auvergne-Rhône-Alpes' },
  { code: '27', name: 'Bourgogne-Franche-Comté' },
  { code: '53', name: 'Bretagne' },
  { code: '24', name: 'Centre-Val de Loire' },
  { code: '94', name: 'Corse' },
  { code: '44', name: 'Grand Est' },
  { code: '32', name: 'Hauts-de-France' },
  { code: '11', name: 'Île-de-France' },
  { code: '28', name: 'Normandie' },
  { code: '75', name: 'Nouvelle-Aquitaine' },
  { code: '76', name: 'Occitanie' },
  { code: '52', name: 'Pays de la Loire' },
  { code: '93', name: "Provence-Alpes-Côte d'Azur" },
  { code: '01', name: 'Guadeloupe' },
  { code: '02', name: 'Martinique' },
  { code: '03', name: 'Guyane' },
  { code: '04', name: 'La Réunion' },
  { code: '06', name: 'Mayotte' },
];

/** Top 50 villes françaises par population (INSEE 2024, codes communes). */
export const FR_CITIES_TOP: ReadonlyArray<FrZone> = [
  { code: '75056', name: 'Paris' },
  { code: '13055', name: 'Marseille' },
  { code: '69123', name: 'Lyon' },
  { code: '31555', name: 'Toulouse' },
  { code: '06088', name: 'Nice' },
  { code: '44109', name: 'Nantes' },
  { code: '34172', name: 'Montpellier' },
  { code: '67482', name: 'Strasbourg' },
  { code: '33063', name: 'Bordeaux' },
  { code: '59350', name: 'Lille' },
  { code: '35238', name: 'Rennes' },
  { code: '51454', name: 'Reims' },
  { code: '76540', name: 'Le Havre' },
  { code: '42218', name: 'Saint-Étienne' },
  { code: '83137', name: 'Toulon' },
  { code: '38185', name: 'Grenoble' },
  { code: '21231', name: 'Dijon' },
  { code: '49007', name: 'Angers' },
  { code: '30189', name: 'Nîmes' },
  { code: '92050', name: 'Villeurbanne' },
  { code: '63113', name: 'Clermont-Ferrand' },
  { code: '76351', name: 'Le Mans' },
  { code: '13001', name: 'Aix-en-Provence' },
  { code: '29019', name: 'Brest' },
  { code: '37261', name: 'Tours' },
  { code: '87085', name: 'Limoges' },
  { code: '54395', name: 'Nancy' },
  { code: '37072', name: 'Amiens' },
  { code: '83144', name: 'Perpignan' },
  { code: '06029', name: 'Cannes' },
  { code: '83036', name: 'Boulogne-Billancourt' },
  { code: '76480', name: 'Rouen' },
  { code: '34027', name: 'Béziers' },
  { code: '21231', name: 'Metz' },
  { code: '35047', name: 'Saint-Denis' },
  { code: '92012', name: 'Argenteuil' },
  { code: '06004', name: 'Antibes' },
  { code: '38516', name: 'Saint-Maur-des-Fossés' },
  { code: '92002', name: 'Asnières-sur-Seine' },
  { code: '92062', name: 'Courbevoie' },
  { code: '92044', name: 'Rueil-Malmaison' },
  { code: '92063', name: 'Issy-les-Moulineaux' },
  { code: '93066', name: 'Saint-Denis' },
  { code: '94028', name: 'Créteil' },
  { code: '94068', name: 'Saint-Maur-des-Fossés' },
  { code: '95127', name: 'Cergy' },
  { code: '95176', name: 'Argenteuil' },
  { code: '78646', name: 'Versailles' },
  { code: '78551', name: 'Saint-Germain-en-Laye' },
  { code: '91228', name: 'Évry-Courcouronnes' },
];

export function getReferentialZones(type: 'department' | 'region' | 'city'): ReadonlyArray<FrZone> {
  switch (type) {
    case 'department': return FR_DEPARTMENTS;
    case 'region':     return FR_REGIONS;
    case 'city':       return FR_CITIES_TOP;
  }
}
